<?php
//Get the current product
//$product = Mage::registry('product');
?>

</style>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Riyada Provider</h4>
    </div>
    <div id="group_fields4" class="fieldset fieldset-wide">
        <h3>Riyada Provider</h3>
    </div>
</div>

<div id="alert_messages_block"><?php echo $this->getMessageHtml() ?></div>


<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">choose provider for this product</h4>
</div>
<div class="fieldset">


    <div class="grid">
        <div class="hor-scroll" >
            <table cellspacing="0" class="data border" id="myTable">
                <col width="1"/>
                <col width="1"/>
                <col width="2" />
                <col width="1" />
                <thead>
                    <tr class="headings">
                        <th>Provider Name<span class="required">*</span></th>

                        <th>Option <d style="margin-left:67% ">Price</d><d style="margin-left:14% ">Availability</d> </th>



                <th>Delete</th>
                </tr>
                </thead>

                <tbody id="ticket_items_body">

                    <tr>
                        <td>

                        </td>
                        <td class="input-price" width="120%">



                            <br>


                        </td>


                        <td>
                        </td>
                    </tr>

                    <?php
                    $idProd = $this->getProduct();
                    $collectProv = Mage::getModel('price/price')->getCollection()
                            ->addFieldToSelect('id_provider')
                            ->addFieldToFilter('id_product', $idProd)
                            ->setOrder('id_provider', 'asc')
                            ->distinct(true)
                            ->getData();

                    $collection = Mage::getModel('riyada_imei/provider')->getCollection();
                    $options = (Mage::getModel('price/price')->optionjs($collection));

                    foreach ($collectProv as $pro) {
                        $id_provider = $pro['id_provider'];
                        $collect = Mage::getModel('price/price')->getCollection()
                                ->addFieldToSelect('id')
                                ->addFieldToSelect('variety')
                                ->addFieldToSelect('price')
                                ->addFieldToSelect('availability')
                                ->addFieldToFilter('id_product', $idProd)
                                ->addFieldToFilter('id_provider', $id_provider)
                                ->setOrder('id', 'asc')
                                ->distinct(true)
                                ->getData();

                        echo ("<tr name='provider' id='provider'>
            <td><select style='font-size:130%; width:102%' id='pro' name='pro' >");
                        foreach ($options as $prov) {
                            if ($prov['value'] == $id_provider)
                                echo" <option value=" . $prov['value'] . " selected>" . $prov['label'] . "</option>";
                            else
                                echo "<option value=" . $prov['value'] . ">" . $prov['label'] . "</option>";
                        }
                        echo "</select></td><td><div>";

                        foreach ($collect as $row) {
                            if ($row['availability'] == 0)
                                $availability = "<option><option value='1'>InStock <option value='0' selected>OutOfStock";
                            else
                                $availability = "<option><option value='1' selected>InStock <option value='0'>OutOfStock";

                            echo ("

       <id  hidden  value='" . $row['id'] . "'>" . $row['id'] . "</id>
           <div>
<input type='text'  value='" . $row['variety'] . "' required='true' style='width:70%' name='variety' placeholder='insert  color and/or mobile capacity'><input value='" . $row['price'] . "' type='text' required='true' placeHolder='price' style='width:17%' name='price' ><select style='width:11%'>" . $availability . "</select></br></div>");

                            ;
                        }
                        echo "<button onclick='myaddFunction(this)' type='button'>add</button></di></td><td><button  id='del' type='button'  class='scalable delete icon-btn delete-ticket-item'><span><span><span>Delete</span></span></span></button></td></tr>";
                    }
                    ?>

                </tbody>


            </table>
            <div id="resulta">     




            </div>

        </div>
    </div>
</div>



<button id='b1' type='button'  class='button'><span><span><span>Add Provider</span></span></span></button>
<button id='b3' type='button'    class='button'><span><span><span>save</span></span></span></button>


<script >

    function save() {

        mytab = new Array();
        var tab = document.body.select('[name=provider]');
        var j = 1;
        var i = 0;
        var k = 0;
        row = new Array();
        row2 = new Array();
        row3 = new Array();
        rowID = new Array();
        var n = 0;
        for (h = 0; h < tab.length; h++) {
            mytab[h] = new Array();

            if (h != 0)
                k = 0;
            row = tab[h].getElementsByTagName('select');
            row2 = tab[h].getElementsByTagName('input');
            row3 = tab[h].getElementsByTagName('id');

            mytab[h][k] = row[0].value;
            j = 1;
            i = 0;

            while (j < row.length) {
                rowID[n] = row3[j - 1].textContent;
                n++;
                mytab[h][k + 1] = row2[i].value
                mytab[h][k + 2] = row2[i + 1].value
                mytab[h][k + 3] = row[j].value;
                j++;
                i = i + 2;
                k = k + 3;
            }

        }


        //console.log(rowID)

        return mytab;


    }

//return id
    function saveid() {

        mytab = new Array();
        var tab = document.body.select('[name=provider]');
        var j = 1;
        var i = 0;
        var k = 0;
        row = new Array();
        row2 = new Array();
        row3 = new Array();
        rowID = new Array();
        var n = 0;
        for (h = 0; h < tab.length; h++) {
            mytab[h] = new Array();

            if (h != 0)
                k = 0;
            row = tab[h].getElementsByTagName('select');
            row2 = tab[h].getElementsByTagName('input');
            row3 = tab[h].getElementsByTagName('id');

            mytab[h][k] = row[0].value;
            j = 1;
            i = 0;

            while (j < row.length) {
                rowID[n] = row3[j - 1].textContent;
                n++;
                mytab[h][k + 1] = row2[i].value
                mytab[h][k + 2] = row2[i + 1].value
                mytab[h][k + 3] = row[j].value;
                j++;
                i = i + 2;
                k = k + 3;
            }

        }


        console.log(rowID)

        return rowID;


    }


function myDeleteFunction(o) {
        var p = o.parentNode.parentNode;
        var t = p.getElementsByTagName('select');
        var a = (t[0].value)
        if(confirm("are you sure"))
        p.parentNode.removeChild(p)
        

    }


    var index = 1;
    function myaddFunction(o) {
        var btn = document.createElement('div');
        btn.id = index;
        btn.innerHTML = "<id hidden value=''></id><input type='text'  name='variety' required='true' style='width:70%' placeholder='insert  color and/or mobile capacity'><input type='text' required='true' style='width:17%' placeholder='Price'><select style='width:11%'><option value='1'>InStock <option value='0'>OutOfStock</select><br><button onclick='myaddFunction(this)'>add</button>";

        var p = o.parentNode;
        p.appendChild(btn);
        p.removeChild(o);
        //  var d=  document.createElement()
        index++;
    }






</script>








<script  type="text/javascript"  src="<?php echo $this->getJsUrl('lib/jquery/jquery-1.10.2.js') ?>"></script>
<script>jQuery.noConflict()</script>
<script  type="text/javascript">

        function myDeletesFunction(o) {
        var p = o.parentNode.parentNode;
        var t = p.getElementsByTagName('select');
        var a = (t[0].value)
       
        // p.parentNode.removeChild(p)
        return a;

    }
    jQuery(document).ready(function () {

        jQuery('#del').click(function ()
        {
            
           if(confirm("are you sure?"))
           {
              
              a= myDeletesFunction(this);
              
              
               jQuery.ajax({
                    url: "<?php echo Mage::getUrl('price/index/deleteB'); ?>",
                    data:{
                        provdel:a,
                        prodId: "<?php echo $this->getProduct() ?>"},
                            type: 'POST',

                
                }).done(function (data) {
                    
                    jQuery('#del').parent().parent().remove();
                });
              
              
              
        }
           
       
    });


    });
   





    jQuery(document).ready(function ($) {

        jQuery(function () {


            $('#del').click(function ()
            {




            });




        });







        var ino = 1;
        jQuery(function () {
            $("#b1").click(function () {
                $(this).parent('tr').attr('id', ino);
                jQuery.ajax({
                    url: "<?php echo Mage::getUrl('price/index/add'); ?>"

                }).done(function (data) {
                    $('#myTable').append(data);
                });
                ino++;
            });
        });
        //deleteB

        //save methode ajax      
        jQuery(function () {
            $("#b3").click(function () {
                mytable = new Array();
                lesID = new Array();
                mytable = save();

                lesID = saveid();
                //console.log(lesID);

                jQuery.ajax({
                    url: "<?php echo Mage::getUrl('price/index/saved'); ?>",
                    data: {mytable: mytable,
                        lesID: lesID,
                        prodId: "<?php echo $this->getProduct() ?>"},
                    type: 'POST',
                }).done(function (data) {
                    alert(data);
                    location.reload();
                    
                });
            });
        });
    });



</script>  

</body>
</html>