<?php
//Get the current product
//$product = Mage::registry('product');
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Custom Tab</h4>
    </div>
    <div id="group_fields4" class="fieldset fieldset-wide">
 <?php
 var_dump($this->getProduct()->getId());
 ?>
    </div>
</div>
<?php $_product = $this->getProduct()?>
<div id="alert_messages_block"><?php echo $this->getMessageHtml() ?></div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->getTabTitle() ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="provider_id">Provider<span class="required">*</span></label></td>
                    <td class="value">
                        <?php
                         var_dump(Mage::getModel('provider/product_attribute_source_provider')->getAllOptions());
                         
                            $select = new Varien_Data_Form_Element_Select(array(
                                'id' => 'provider_id',
                                'name' => 'product[provider_id]',
                                'value' => $_product->getData('provider_id'),
                               // 'values' => Mage::getModel('provider/product_attribute_source_provider')->getAllOptions(),
                                'required' => true
                            ));
                            $select->setForm($this);
                            echo $select->toHtml();
                        ?>
                    </td>
                </tr>
            </tbody>
        </table>
        <?php /*
        <div class="grid">
            <div class="hor-scroll">
                <table cellspacing="0" class="data border">
                    <col />
                    <col width="1"/>
                    <col width="1" />
                    <col width="1" />
                    <thead>
                        <tr class="headings">
                            <th><?php echo Mage::helper('customtabs')->__('Title')?> <span class="required">*</span></th>
                            <?php if ($this->getCanReadPrice() !== false) : ?>
                            <th><?php echo Mage::helper('customtabs')->__('Price')?></th>
                            <?php endif; ?>
                            <th><span class="nobr"><?php echo Mage::helper('customtabs')->__('Sort Order')?></span></th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="4" class="a-right"><?php echo $this->getAddButtonHtml()?></td>
                        </tr>
                    </tfoot>
                    <tbody id="ticket_items_body">
                    </tbody>
                </table>
            </div>
        </div>
    </div> */?>